options:
  logging: CLOUD_LOGGING_ONLY  # or NONE, if you don't want logs to be stored

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

images:
  - 'gcr.io/$PROJECT_ID/my-app'

