steps:
  # Step 1: Authenticate using the service account
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
    env:
      - 'GCLOUD_SERVICE_KEY=${_GCLOUD_SERVICE_KEY}'

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sonorous-saga-427507-v9/my-app', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sonorous-saga-427507-v9/my-app']

  # Step 4: Deploy the Docker image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/my-app-deployment'
      - 'my-app-container=gcr.io/sonorous-saga-427507-v9/my-app'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

images:
  - 'gcr.io/sonorous-saga-427507-v9/my-app'

options:
  logging: CLOUD_LOGGING_ONLY  # or NONE, if you don't want logs to be stored
